WITH TRIPS as (

SELECT
RIDE_ID,
RIDEABLE_TYPE,
TO_TIMESTAMP(STARTED_AT) AS TRIP_DATAE,
START_STATIO_ID AS START_STATION_ID,
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT),TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECONDS
FROM {{ source('demo', 'bike') }}
LIMIT 10
)

SELECT *
FROM TRIPS

